// <auto-generated />
using System;
using EyewearStore_SWP391.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EyewearStore_SWP391.Migrations
{
    [DbContext(typeof(EyewearStoreContext))]
    [Migration("20260214014242_AddPrescriptionIdAndFeeToCartItem")]
    partial class AddPrescriptionIdAndFeeToCartItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EyewearStore_SWP391.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address_line");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("receiver_name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.BundleItem", b =>
                {
                    b.Property<int>("BundleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bundle_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BundleItemId"));

                    b.Property<int>("BundleProductId")
                        .HasColumnType("int")
                        .HasColumnName("bundle_product_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.HasKey("BundleItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("BundleProductId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UQ_bundle_items");

                    b.ToTable("bundle_items", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_carts_user");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cart_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    b.Property<decimal>("PrescriptionFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("prescription_fee");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("prescription_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.Property<string>("TempPrescriptionJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("temp_prescription_json");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId")
                        .HasDatabaseName("IX_cart_items_cart");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ServiceId");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<string>("StripeSessionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("stripe_session_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressId");

                    b.HasIndex("StripeSessionId")
                        .HasDatabaseName("IX_orders_stripe_session");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_orders_user");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<bool>("IsBundle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_bundle");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<decimal>("PrescriptionFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("prescription_fee");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("prescription_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("snapshot_json");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_order_items_order");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.PrescriptionProfile", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("prescription_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<int?>("LeftAxis")
                        .HasColumnType("int")
                        .HasColumnName("left_axis");

                    b.Property<decimal?>("LeftCyl")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("left_cyl");

                    b.Property<decimal?>("LeftSph")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("left_sph");

                    b.Property<string>("ProfileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("profile_name");

                    b.Property<int?>("RightAxis")
                        .HasColumnType("int")
                        .HasColumnName("right_axis");

                    b.Property<decimal?>("RightCyl")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("right_cyl");

                    b.Property<decimal?>("RightSph")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("right_sph");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("prescription_profiles", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Attributes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attributes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("InventoryQty")
                        .HasColumnType("int")
                        .HasColumnName("inventory_qty");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("product_type");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductType")
                        .HasDatabaseName("IX_product_type");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UQ_product_sku");

                    b.ToTable("product", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("alt_text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_product_images_product");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Return", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("return_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int")
                        .HasColumnName("order_item_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("ReturnId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("returns", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("ServiceId");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentId"));

                    b.Property<string>("Carrier")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("carrier");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("delivered_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("shipped_at");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tracking_number");

                    b.HasKey("ShipmentId");

                    b.HasIndex("OrderId");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.ShipmentStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("history_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("HistoryId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("shipment_status_history", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wishlist_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("NotifyOnRestock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_on_restock");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("WishlistId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_wishlist_user");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("UQ_wishlist_user_product");

                    b.ToTable("wishlist", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Bundle", b =>
                {
                    b.HasBaseType("EyewearStore_SWP391.Models.Product");

                    b.Property<string>("BundleNote")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bundle_note");

                    b.ToTable("bundles", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Frame", b =>
                {
                    b.HasBaseType("EyewearStore_SWP391.Models.Product");

                    b.Property<decimal?>("BridgeWidth")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("bridge_width");

                    b.Property<string>("FrameMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("frame_material");

                    b.Property<string>("FrameType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("frame_type");

                    b.Property<decimal?>("TempleLength")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("temple_length");

                    b.ToTable("frames", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Lens", b =>
                {
                    b.HasBaseType("EyewearStore_SWP391.Models.Product");

                    b.Property<bool>("IsPrescription")
                        .HasColumnType("bit")
                        .HasColumnName("is_prescription");

                    b.Property<decimal?>("LensIndex")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("lens_index");

                    b.Property<string>("LensType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lens_type");

                    b.Property<decimal?>("PrescriptionFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("prescription_fee");

                    b.ToTable("lenses", (string)null);
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Address", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_addresses_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.BundleItem", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.Bundle", "BundleProduct")
                        .WithMany("BundleItems")
                        .HasForeignKey("BundleProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_bundle_items_bundle");

                    b.HasOne("EyewearStore_SWP391.Models.Product", "Product")
                        .WithMany("ContainedInBundles")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_bundle_items_product");

                    b.Navigation("BundleProduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Cart", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_carts_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.CartItem", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_cart_items_cart");

                    b.HasOne("EyewearStore_SWP391.Models.PrescriptionProfile", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_cart_items_prescription");

                    b.HasOne("EyewearStore_SWP391.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_cart_items_product");

                    b.HasOne("EyewearStore_SWP391.Models.Service", "Service")
                        .WithMany("CartItems")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_cart_items_service");

                    b.Navigation("Cart");

                    b.Navigation("Prescription");

                    b.Navigation("Product");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Order", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK_orders_addresses");

                    b.HasOne("EyewearStore_SWP391.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_orders_users");

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.OrderItem", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_order_items_orders");

                    b.HasOne("EyewearStore_SWP391.Models.PrescriptionProfile", "Prescription")
                        .WithMany("OrderItems")
                        .HasForeignKey("PrescriptionId")
                        .HasConstraintName("FK_order_items_prescription");

                    b.HasOne("EyewearStore_SWP391.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_order_items_product");

                    b.Navigation("Order");

                    b.Navigation("Prescription");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.PrescriptionProfile", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.User", "User")
                        .WithMany("PrescriptionProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_prescription_profiles_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.ProductImage", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_product_images_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Return", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.OrderItem", "OrderItem")
                        .WithMany("Returns")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_returns_order_items");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Shipment", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_shipments_orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.ShipmentStatusHistory", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.Shipment", "Shipment")
                        .WithMany("ShipmentStatusHistories")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_shipment_history_shipments");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Wishlist", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_wishlist_product");

                    b.HasOne("EyewearStore_SWP391.Models.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_wishlist_users");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Bundle", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("EyewearStore_SWP391.Models.Bundle", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Frame", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("EyewearStore_SWP391.Models.Frame", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Lens", b =>
                {
                    b.HasOne("EyewearStore_SWP391.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("EyewearStore_SWP391.Models.Lens", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.OrderItem", b =>
                {
                    b.Navigation("Returns");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.PrescriptionProfile", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("ContainedInBundles");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductImages");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Service", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Shipment", b =>
                {
                    b.Navigation("ShipmentStatusHistories");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("PrescriptionProfiles");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("EyewearStore_SWP391.Models.Bundle", b =>
                {
                    b.Navigation("BundleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
